--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsToxicGG/ThrowableFireball
build-by-default: true
branches:
- main
projects:
  ThrowableFireball:
    path: ""
    icon: "icon.png"
...
